version: "3"
services:
  app:
    image: hrms:latest
    build:
      dockerfile: Dockerfile.multistage
      context: .
    ports:
      - 3000:3000
    networks:
      - fiberhrms
    restart: unless-stopped
    depends_on:
      - mongo
  mongo:
      image: mongo
      restart: unless-stopped
      ports:
        - 27017:27017
      networks:
      - fiberhrms  
networks:
  fiberhrms:
     driver: bridge
volumes:
  mongo-data:
    driver: local